// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/close.proto

package autogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fd          uint32                 `protobuf:"varint,1,opt,name=fd"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_close_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_close_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseRequest) GetFd() uint32 {
	if x != nil {
		return x.xxx_hidden_Fd
	}
	return 0
}

func (x *CloseRequest) SetFd(v uint32) {
	x.xxx_hidden_Fd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CloseRequest) HasFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CloseRequest) ClearFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Fd = 0
}

type CloseRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Fd *uint32
}

func (b0 CloseRequest_builder) Build() *CloseRequest {
	m0 := &CloseRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Fd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Fd = *b.Fd
	}
	return m0
}

var File_proto_close_proto protoreflect.FileDescriptor

const file_proto_close_proto_rawDesc = "" +
	"\n" +
	"\x11proto/close.proto\"\x1e\n" +
	"\fCloseRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\rR\x02fdB,Z*github.com/therealtunge/backgammon/autogenb\beditionsp\xe9\a"

var file_proto_close_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_close_proto_goTypes = []any{
	(*CloseRequest)(nil), // 0: CloseRequest
}
var file_proto_close_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_close_proto_init() }
func file_proto_close_proto_init() {
	if File_proto_close_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_close_proto_rawDesc), len(file_proto_close_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_close_proto_goTypes,
		DependencyIndexes: file_proto_close_proto_depIdxs,
		MessageInfos:      file_proto_close_proto_msgTypes,
	}.Build()
	File_proto_close_proto = out.File
	file_proto_close_proto_goTypes = nil
	file_proto_close_proto_depIdxs = nil
}
