// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/connect.proto

package autogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetType int32

const (
	NetType_TCP NetType = 0
	NetType_UDP NetType = 1
	NetType_TLS NetType = 2
)

// Enum value maps for NetType.
var (
	NetType_name = map[int32]string{
		0: "TCP",
		1: "UDP",
		2: "TLS",
	}
	NetType_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
		"TLS": 2,
	}
)

func (x NetType) Enum() *NetType {
	p := new(NetType)
	*p = x
	return p
}

func (x NetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_connect_proto_enumTypes[0].Descriptor()
}

func (NetType) Type() protoreflect.EnumType {
	return &file_proto_connect_proto_enumTypes[0]
}

func (x NetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConnectRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Dest        *string                `protobuf:"bytes,1,opt,name=dest"`
	xxx_hidden_Type        NetType                `protobuf:"varint,2,opt,name=type,enum=NetType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectRequest) GetDest() string {
	if x != nil {
		if x.xxx_hidden_Dest != nil {
			return *x.xxx_hidden_Dest
		}
		return ""
	}
	return ""
}

func (x *ConnectRequest) GetType() NetType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return NetType_TCP
}

func (x *ConnectRequest) SetDest(v string) {
	x.xxx_hidden_Dest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConnectRequest) SetType(v NetType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConnectRequest) HasDest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConnectRequest) ClearDest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Dest = nil
}

func (x *ConnectRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = NetType_TCP
}

type ConnectRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Dest *string
	Type *NetType
}

func (b0 ConnectRequest_builder) Build() *ConnectRequest {
	m0 := &ConnectRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Dest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Dest = b.Dest
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Type = *b.Type
	}
	return m0
}

var File_proto_connect_proto protoreflect.FileDescriptor

const file_proto_connect_proto_rawDesc = "" +
	"\n" +
	"\x13proto/connect.proto\"B\n" +
	"\x0eConnectRequest\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\tR\x04dest\x12\x1c\n" +
	"\x04type\x18\x02 \x01(\x0e2\b.NetTypeR\x04type*$\n" +
	"\aNetType\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\a\n" +
	"\x03TLS\x10\x02B,Z*github.com/therealtunge/backgammon/autogenb\beditionsp\xe9\a"

var file_proto_connect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_connect_proto_goTypes = []any{
	(NetType)(0),           // 0: NetType
	(*ConnectRequest)(nil), // 1: ConnectRequest
}
var file_proto_connect_proto_depIdxs = []int32{
	0, // 0: ConnectRequest.type:type_name -> NetType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_connect_proto_init() }
func file_proto_connect_proto_init() {
	if File_proto_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connect_proto_rawDesc), len(file_proto_connect_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_connect_proto_goTypes,
		DependencyIndexes: file_proto_connect_proto_depIdxs,
		EnumInfos:         file_proto_connect_proto_enumTypes,
		MessageInfos:      file_proto_connect_proto_msgTypes,
	}.Build()
	File_proto_connect_proto = out.File
	file_proto_connect_proto_goTypes = nil
	file_proto_connect_proto_depIdxs = nil
}
