// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/message.proto

package autogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_CONN  Type = 0
	Type_TYPE_CLOSE Type = 1
	Type_TYPE_READ  Type = 2
	Type_TYPE_WRITE Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_CONN",
		1: "TYPE_CLOSE",
		2: "TYPE_READ",
		3: "TYPE_WRITE",
	}
	Type_value = map[string]int32{
		"TYPE_CONN":  0,
		"TYPE_CLOSE": 1,
		"TYPE_READ":  2,
		"TYPE_WRITE": 3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Request struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Password    *string                `protobuf:"bytes,1,opt,name=password"`
	xxx_hidden_T           Type                   `protobuf:"varint,2,opt,name=t,enum=Type"`
	xxx_hidden_Req         isRequest_Req          `protobuf_oneof:"req"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Request) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *Request) GetT() Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_T
		}
	}
	return Type_TYPE_CONN
}

func (x *Request) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Req.(*request_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *Request) GetClose() *CloseRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Req.(*request_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *Request) GetRead() *ReadRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Req.(*request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetWrite() *WriteRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Req.(*request_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *Request) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Request) SetT(v Type) {
	x.xxx_hidden_T = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Request) SetConnect(v *ConnectRequest) {
	if v == nil {
		x.xxx_hidden_Req = nil
		return
	}
	x.xxx_hidden_Req = &request_Connect{v}
}

func (x *Request) SetClose(v *CloseRequest) {
	if v == nil {
		x.xxx_hidden_Req = nil
		return
	}
	x.xxx_hidden_Req = &request_Close{v}
}

func (x *Request) SetRead(v *ReadRequest) {
	if v == nil {
		x.xxx_hidden_Req = nil
		return
	}
	x.xxx_hidden_Req = &request_Read{v}
}

func (x *Request) SetWrite(v *WriteRequest) {
	if v == nil {
		x.xxx_hidden_Req = nil
		return
	}
	x.xxx_hidden_Req = &request_Write{v}
}

func (x *Request) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Request) HasT() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Request) HasReq() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Req != nil
}

func (x *Request) HasConnect() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Req.(*request_Connect)
	return ok
}

func (x *Request) HasClose() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Req.(*request_Close)
	return ok
}

func (x *Request) HasRead() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Req.(*request_Read)
	return ok
}

func (x *Request) HasWrite() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Req.(*request_Write)
	return ok
}

func (x *Request) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Password = nil
}

func (x *Request) ClearT() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_T = Type_TYPE_CONN
}

func (x *Request) ClearReq() {
	x.xxx_hidden_Req = nil
}

func (x *Request) ClearConnect() {
	if _, ok := x.xxx_hidden_Req.(*request_Connect); ok {
		x.xxx_hidden_Req = nil
	}
}

func (x *Request) ClearClose() {
	if _, ok := x.xxx_hidden_Req.(*request_Close); ok {
		x.xxx_hidden_Req = nil
	}
}

func (x *Request) ClearRead() {
	if _, ok := x.xxx_hidden_Req.(*request_Read); ok {
		x.xxx_hidden_Req = nil
	}
}

func (x *Request) ClearWrite() {
	if _, ok := x.xxx_hidden_Req.(*request_Write); ok {
		x.xxx_hidden_Req = nil
	}
}

const Request_Req_not_set_case case_Request_Req = 0
const Request_Connect_case case_Request_Req = 3
const Request_Close_case case_Request_Req = 4
const Request_Read_case case_Request_Req = 5
const Request_Write_case case_Request_Req = 6

func (x *Request) WhichReq() case_Request_Req {
	if x == nil {
		return Request_Req_not_set_case
	}
	switch x.xxx_hidden_Req.(type) {
	case *request_Connect:
		return Request_Connect_case
	case *request_Close:
		return Request_Close_case
	case *request_Read:
		return Request_Read_case
	case *request_Write:
		return Request_Write_case
	default:
		return Request_Req_not_set_case
	}
}

type Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Password *string
	T        *Type
	// Fields of oneof xxx_hidden_Req:
	Connect *ConnectRequest
	Close   *CloseRequest
	Read    *ReadRequest
	Write   *WriteRequest
	// -- end of xxx_hidden_Req
}

func (b0 Request_builder) Build() *Request {
	m0 := &Request{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Password = b.Password
	}
	if b.T != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_T = *b.T
	}
	if b.Connect != nil {
		x.xxx_hidden_Req = &request_Connect{b.Connect}
	}
	if b.Close != nil {
		x.xxx_hidden_Req = &request_Close{b.Close}
	}
	if b.Read != nil {
		x.xxx_hidden_Req = &request_Read{b.Read}
	}
	if b.Write != nil {
		x.xxx_hidden_Req = &request_Write{b.Write}
	}
	return m0
}

type case_Request_Req protoreflect.FieldNumber

func (x case_Request_Req) String() string {
	md := file_proto_message_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRequest_Req interface {
	isRequest_Req()
}

type request_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,3,opt,name=connect,oneof"`
}

type request_Close struct {
	Close *CloseRequest `protobuf:"bytes,4,opt,name=close,oneof"`
}

type request_Read struct {
	Read *ReadRequest `protobuf:"bytes,5,opt,name=read,oneof"`
}

type request_Write struct {
	Write *WriteRequest `protobuf:"bytes,6,opt,name=write,oneof"`
}

func (*request_Connect) isRequest_Req() {}

func (*request_Close) isRequest_Req() {}

func (*request_Read) isRequest_Req() {}

func (*request_Write) isRequest_Req() {}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x1a\x13proto/connect.proto\x1a\x11proto/close.proto\x1a\x10proto/read.proto\x1a\x11proto/write.proto\"\xe0\x01\n" +
	"\aRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x13\n" +
	"\x01t\x18\x02 \x01(\x0e2\x05.TypeR\x01t\x12+\n" +
	"\aconnect\x18\x03 \x01(\v2\x0f.ConnectRequestH\x00R\aconnect\x12%\n" +
	"\x05close\x18\x04 \x01(\v2\r.CloseRequestH\x00R\x05close\x12\"\n" +
	"\x04read\x18\x05 \x01(\v2\f.ReadRequestH\x00R\x04read\x12%\n" +
	"\x05write\x18\x06 \x01(\v2\r.WriteRequestH\x00R\x05writeB\x05\n" +
	"\x03req*D\n" +
	"\x04Type\x12\r\n" +
	"\tTYPE_CONN\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_CLOSE\x10\x01\x12\r\n" +
	"\tTYPE_READ\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_WRITE\x10\x03B,Z*github.com/therealtunge/backgammon/autogenb\beditionsp\xe9\a"

var file_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_message_proto_goTypes = []any{
	(Type)(0),              // 0: Type
	(*Request)(nil),        // 1: Request
	(*ConnectRequest)(nil), // 2: ConnectRequest
	(*CloseRequest)(nil),   // 3: CloseRequest
	(*ReadRequest)(nil),    // 4: ReadRequest
	(*WriteRequest)(nil),   // 5: WriteRequest
}
var file_proto_message_proto_depIdxs = []int32{
	0, // 0: Request.t:type_name -> Type
	2, // 1: Request.connect:type_name -> ConnectRequest
	3, // 2: Request.close:type_name -> CloseRequest
	4, // 3: Request.read:type_name -> ReadRequest
	5, // 4: Request.write:type_name -> WriteRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_connect_proto_init()
	file_proto_close_proto_init()
	file_proto_read_proto_init()
	file_proto_write_proto_init()
	file_proto_message_proto_msgTypes[0].OneofWrappers = []any{
		(*request_Connect)(nil),
		(*request_Close)(nil),
		(*request_Read)(nil),
		(*request_Write)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		EnumInfos:         file_proto_message_proto_enumTypes,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
