// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/response.proto

package autogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// response
type Response struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_R  isResponse_R           `protobuf_oneof:"r"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Response) GetFd() uint32 {
	if x != nil {
		if x, ok := x.xxx_hidden_R.(*response_Fd); ok {
			return x.Fd
		}
	}
	return 0
}

func (x *Response) GetData() string {
	if x != nil {
		if x, ok := x.xxx_hidden_R.(*response_Data); ok {
			return x.Data
		}
	}
	return ""
}

func (x *Response) GetError() string {
	if x != nil {
		if x, ok := x.xxx_hidden_R.(*response_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Response) SetFd(v uint32) {
	x.xxx_hidden_R = &response_Fd{v}
}

func (x *Response) SetData(v string) {
	x.xxx_hidden_R = &response_Data{v}
}

func (x *Response) SetError(v string) {
	x.xxx_hidden_R = &response_Error{v}
}

func (x *Response) HasR() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_R != nil
}

func (x *Response) HasFd() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_R.(*response_Fd)
	return ok
}

func (x *Response) HasData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_R.(*response_Data)
	return ok
}

func (x *Response) HasError() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_R.(*response_Error)
	return ok
}

func (x *Response) ClearR() {
	x.xxx_hidden_R = nil
}

func (x *Response) ClearFd() {
	if _, ok := x.xxx_hidden_R.(*response_Fd); ok {
		x.xxx_hidden_R = nil
	}
}

func (x *Response) ClearData() {
	if _, ok := x.xxx_hidden_R.(*response_Data); ok {
		x.xxx_hidden_R = nil
	}
}

func (x *Response) ClearError() {
	if _, ok := x.xxx_hidden_R.(*response_Error); ok {
		x.xxx_hidden_R = nil
	}
}

const Response_R_not_set_case case_Response_R = 0
const Response_Fd_case case_Response_R = 1
const Response_Data_case case_Response_R = 2
const Response_Error_case case_Response_R = 3

func (x *Response) WhichR() case_Response_R {
	if x == nil {
		return Response_R_not_set_case
	}
	switch x.xxx_hidden_R.(type) {
	case *response_Fd:
		return Response_Fd_case
	case *response_Data:
		return Response_Data_case
	case *response_Error:
		return Response_Error_case
	default:
		return Response_R_not_set_case
	}
}

type Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_R:
	// for connect
	Fd *uint32
	// for read
	Data  *string
	Error *string
	// -- end of xxx_hidden_R
}

func (b0 Response_builder) Build() *Response {
	m0 := &Response{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Fd != nil {
		x.xxx_hidden_R = &response_Fd{*b.Fd}
	}
	if b.Data != nil {
		x.xxx_hidden_R = &response_Data{*b.Data}
	}
	if b.Error != nil {
		x.xxx_hidden_R = &response_Error{*b.Error}
	}
	return m0
}

type case_Response_R protoreflect.FieldNumber

func (x case_Response_R) String() string {
	md := file_proto_response_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isResponse_R interface {
	isResponse_R()
}

type response_Fd struct {
	// for connect
	Fd uint32 `protobuf:"varint,1,opt,name=fd,oneof"`
}

type response_Data struct {
	// for read
	Data string `protobuf:"bytes,2,opt,name=data,oneof"`
}

type response_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,oneof"`
}

func (*response_Fd) isResponse_R() {}

func (*response_Data) isResponse_R() {}

func (*response_Error) isResponse_R() {}

var File_proto_response_proto protoreflect.FileDescriptor

const file_proto_response_proto_rawDesc = "" +
	"\n" +
	"\x14proto/response.proto\"O\n" +
	"\bResponse\x12\x10\n" +
	"\x02fd\x18\x01 \x01(\rH\x00R\x02fd\x12\x14\n" +
	"\x04data\x18\x02 \x01(\tH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\x03\n" +
	"\x01rB,Z*github.com/therealtunge/backgammon/autogenb\beditionsp\xe9\a"

var file_proto_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_response_proto_goTypes = []any{
	(*Response)(nil), // 0: Response
}
var file_proto_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_response_proto_init() }
func file_proto_response_proto_init() {
	if File_proto_response_proto != nil {
		return
	}
	file_proto_response_proto_msgTypes[0].OneofWrappers = []any{
		(*response_Fd)(nil),
		(*response_Data)(nil),
		(*response_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_response_proto_rawDesc), len(file_proto_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_response_proto_goTypes,
		DependencyIndexes: file_proto_response_proto_depIdxs,
		MessageInfos:      file_proto_response_proto_msgTypes,
	}.Build()
	File_proto_response_proto = out.File
	file_proto_response_proto_goTypes = nil
	file_proto_response_proto_depIdxs = nil
}
